---
title: "DACSS Storyboard"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(flexdashboard)
library(dplyr)
library(ggplot2)
```

## Sidebar {.sidebar}


Preparing the dashboard based on the instructions given at @magallanes_reyes_data_2022, and @aden-buie_flexdashboard_2024.

## Column {.tabset .tabset-fade}


### Categorical Bar Plot

```{r}
locale_summary <- mydata %>%
  group_by(LocaleType) %>%
  summarise(School_Count = n(), .groups = 'drop')

base_plot <- ggplot(data = locale_summary, aes(x = LocaleType, y = School_Count))
my_barplot <- base_plot +
  geom_bar(stat = 'identity', fill = "#2C7BB6", color = "black") +
  labs(
    title = "Schools by Location",
    subtitle = "School Locations in Washington State (2019)",
    x = "Locale Type",
    y = "Number of Schools",
    caption = "Data Source: US Department of Education"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(face = "bold", size = 16, color = "#1D3557"),
    plot.subtitle = element_text(size = 12, color = "#457B9D"),
    axis.title.x = element_text(size = 12),
    axis.title.y = element_text(size = 12)
  )
my_barplot

saveRDS(my_barplot, file = "barplot.rds")
```


### Histogram

```{r}

```

### Scatterplot

```{r}

```


### Map

```{r}

```


### References 
